baseURL = 'https://17xande.netlify.app'
languageCode = 'en-uk'
title = '17Xande'

theme = 'github.com/LordMathis/hugo-theme-nightfall'

[params]
author = "Alexandre Figueiredo"
user = "Alex"
hostname = "17xande.netlify.app"

  [[params.social]]
  key = 0
  name = "github"
  url = "https://github.com/17xande"

[menu]
  [[menu.header]]
  name = "posts"
  weight = 0
  url = "/posts"

